---
title: "DC3 Book Category Visualization"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    source_code: embed
    theme: united
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
#data cleaning
library(dplyr)
library(tidyverse)
library(data.table)
#for network
library(visNetwork)
#for tree
library(collapsibleTree)
#for plot
library(ggplot2)
library(plotly)
library(colorspace)
Bookworld<-readRDS("Bookworld3.RData")
bookpci<-readRDS("bookpwithcatid.RData")
nodename<-readRDS("nodehovertip2.RData")
edges<-readRDS("edge2.RData")
```

Tree and Graphs
=================================================================

Column{.sidebar}
-----------------------------------------------------------------------
### Find an ideal category for your product!

```{r}
selectizeInput('interested',label="Category of Interest",
               choices = bookpci$catid, multiple = T,
               options = list(maxItems = 100, placeholder = 'Select a category'),
               selected = bookpci$catid[2])
interestdf<-reactive({
  bookpci%>%
  filter(catid %in% input$interested)
})


```


Column
-----------------------------------------------------------------------

### Book Category Trees

```{r}
#plot collapsible Tree with All data
renderCollapsibleTree(
 collapsibleTreeSummary(
  Bookworld,
  hierarchy=c("level_1","level_2","level_3","level_4","level_5","level_6","level_7"),
  fontSize = 5,
  tooltip=T,
  attribute = "productCount",
))
```


Column
-----------------------------------------------------------------------
### Relatives for any specified category

```{r}
selectInput('bookcategory','Find relatives for a specific category',bookpci$catid,selected = bookpci$catid[2])

selectedID<-reactive({
  bookpci%>%
  filter(catid==input$bookcategory)%>%
  pull(id)%>%
  as.numeric()+1
})

selectedalsoCount<-reactive({
  bookpci%>%
  filter(catid==input$bookcategory)%>%
  pull(alsoCount)
})

selectednodes<-reactive({
  nodename[[toString(selectedID())]]
})
selectededges<-reactive({
  edges[[toString(selectedID())]]
})


renderVisNetwork(
  visNetwork(selectednodes(),selectededges(),main=paste("Also Pair Count: ",selectedalsoCount()))%>%
    visNodes(color=list(highlight="red"))
)
```

Summary scatter plot
=================================================================
### Scatter plot for category of interest
```{r}
renderPlotly({
  p<-ggplot(interestdf(), 
            aes(x = productCount,y=alsoCount,text=paste("Category: ", name,"<br>ID: ",id))) +
        geom_point()+
        theme_minimal()
  ggplotly(p)
})
  

```
